# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\"\x07\n\x05\x45mpty\"1\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04word\x18\x02 \x01(\t\x12\x0f\n\x07meaning\x18\x03 \x01(\t\"!\n\tTermsList\x12\x14\n\x05terms\x18\x01 \x03(\x0b\x32\x05.Term\"2\n\x11\x43reateTermRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0f\n\x07meaning\x18\x02 \x01(\t\"%\n\x12\x43reateTermResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0eGetTermRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\x0fGetTermResponse\x12\x13\n\x04term\x18\x01 \x01(\x0b\x32\x05.Term\"(\n\x11UpdateTermRequest\x12\x13\n\x04term\x18\x01 \x01(\x0b\x32\x05.Term\"%\n\x12UpdateTermResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x11\x44\x65leteTermRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteTermResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x80\x02\n\x08Glossary\x12!\n\x0bGetAllTerms\x12\x06.Empty\x1a\n.TermsList\x12\x35\n\nCreateTerm\x12\x12.CreateTermRequest\x1a\x13.CreateTermResponse\x12,\n\x07GetTerm\x12\x0f.GetTermRequest\x1a\x10.GetTermResponse\x12\x35\n\nUpdateTerm\x12\x12.UpdateTermRequest\x1a\x13.UpdateTermResponse\x12\x35\n\nDeleteTerm\x12\x12.DeleteTermRequest\x1a\x13.DeleteTermResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_TERM']._serialized_start=27
  _globals['_TERM']._serialized_end=76
  _globals['_TERMSLIST']._serialized_start=78
  _globals['_TERMSLIST']._serialized_end=111
  _globals['_CREATETERMREQUEST']._serialized_start=113
  _globals['_CREATETERMREQUEST']._serialized_end=163
  _globals['_CREATETERMRESPONSE']._serialized_start=165
  _globals['_CREATETERMRESPONSE']._serialized_end=202
  _globals['_GETTERMREQUEST']._serialized_start=204
  _globals['_GETTERMREQUEST']._serialized_end=232
  _globals['_GETTERMRESPONSE']._serialized_start=234
  _globals['_GETTERMRESPONSE']._serialized_end=272
  _globals['_UPDATETERMREQUEST']._serialized_start=274
  _globals['_UPDATETERMREQUEST']._serialized_end=314
  _globals['_UPDATETERMRESPONSE']._serialized_start=316
  _globals['_UPDATETERMRESPONSE']._serialized_end=353
  _globals['_DELETETERMREQUEST']._serialized_start=355
  _globals['_DELETETERMREQUEST']._serialized_end=386
  _globals['_DELETETERMRESPONSE']._serialized_start=388
  _globals['_DELETETERMRESPONSE']._serialized_end=425
  _globals['_GLOSSARY']._serialized_start=428
  _globals['_GLOSSARY']._serialized_end=684
# @@protoc_insertion_point(module_scope)
