GET http://127.0.0.1:8000/terms HTTP/1.1

###

GET http://127.0.0.1:8000/terms/3 HTTP/1.1

###

POST http://127.0.0.1:8000/terms HTTP/1.1
content-type: application/json

{
    "word": "Архитектура программы",
    "meaning": "Структурное представление программной системы, включающее описание компонентов, их взаимодействий, поведения и ограничений."
}

###

POST http://127.0.0.1:8000/terms HTTP/1.1
content-type: application/json

{
    "word": "Контейнеризация",
    "meaning": "Технология упаковки программного обеспечения и всех его зависимостей в изолированный контейнер для обеспечения согласованности среды выполнения на разных платформах."
}

###

POST http://127.0.0.1:8000/terms HTTP/1.1
content-type: application/json

{
    "word": "Непрерывное развертывание",
    "meaning": "Подход в разработке программного обеспечения, при котором изменения в коде автоматически проходят все этапы подготовки и развертываются на рабочем сервере без ручного вмешательства."
}

###

PUT http://127.0.0.1:8000/terms HTTP/1.1
content-type: application/json

{
  "term": {
    "id": "1",
    "word": "Архитектура программной системы",
    "meaning": "Новое значение термина"
  }
}

###

DELETE http://127.0.0.1:8000/terms/3 HTTP/1.1
content-type: application/json
